### ISSUE TITLE
Seems like not working!

### ISSUE THREAD

**Issue by victorkardel** [jsjayfiled/react-ts-vite-linaria-boilerplate#2]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/75961352/207371945-fbf2b6a9-9248-485b-af88-fbcb4eabb4a6.png">

Getting this strange error on it, I trying to solve, if I could i will update for you too

**Comment by victorkardel** [comment]
I created an new branch but don't have permission to push but basically it's just change linaria outdated plugin for this one

<img width="765" alt="image" src="https://user-images.githubusercontent.com/75961352/207374846-6feef548-c9a4-4f73-8102-17494e98b8d0.png">

**Comment by jsjayfiled** [comment]
Thanks @vcctm !
I didn't even notice because I deployed to netlify and it was building ok, I appreciate the bump!

**Comment by jsjayfiled** [comment]
> I created an new branch but don't have permission to push but basically it's just change linaria outdated plugin for this one
> 
> <img alt="image" width="765" src="https://user-images.githubusercontent.com/75961352/207374846-6feef548-c9a4-4f73-8102-17494e98b8d0.png">

I've added you as a contributor, could you please push your branch?  I think a lot of people will be looking to bootstrap their projects with these two tools as businesses find out how much styled components add to page load times in huge projects.

**Comment by victorkardel** [comment]
Will do sorry about the late!

**Comment by victorkardel** [comment]
PR Created: https://github.com/jsjayfiled/react-ts-vite-linaria-boilerplate/pull/3
